---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    addon: canal-operator
  name: canal-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      addon: canal-operator
  template:
    metadata:
      labels:
        addon: canal-operator
    spec:
      imagePullSecrets: ${IMAGE_PULL_SECRETS}
      containers:
        - command:
            - /canal-operator
          args:
            - --leader-elect
          image: ${IMAGE_REGISTRY}/erda-addons/canal-operator:1.3
          imagePullPolicy: ${IMAGE_PULL_POLICY}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          name: canal-operator
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      serviceAccountName: canal-operator
      terminationGracePeriodSeconds: 10
