apiVersion: v1
kind: Service
metadata:
  labels:
    addon: canal-operator
  name: canal-operator-metrics-service
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    addon: canal-operator
