# permissions for end users to edit canals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: canal-operator-editor-role
rules:
  - apiGroups:
      - database.erda.cloud
    resources:
      - canals
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - database.erda.cloud
    resources:
      - canals/status
    verbs:
      - get
