---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: canal-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.erda.cloud
  resources:
  - canals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.erda.cloud
  resources:
  - canals/finalizers
  verbs:
  - update
- apiGroups:
  - database.erda.cloud
  resources:
  - canals/status
  verbs:
  - get
  - patch
  - update
